- conn.go
By locking the writer before checking the connection state we're able to guarantee the flusher is not closed before we write to it. 
Fixes https://github.com/Loophole-Labs/frisbee/issues/18
Please update the title of this PR to reflect the type of change.
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`), 
```shell
❯ go test -bench=. ./...
goos: …
```
> fix: Fixing ISSUE-18 where writing to a closed channel causes a panic

- README.md
- client.go
- conn.go
- conn_test.go
- doc.go
- frisbee.go
- server.go
- server_test.go
Allowing io.Copy functionality within Frisbee connections
Fixes LOOP-102-LINEAR
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`), 
```shell
goos: darwin
goarch: amd64
pkg: github.com/loophole-labs/frisbee
cpu: Intel(R) Core(TM) i9-9880H CPU @ …
```
> feat: (loop 103) implement io copy functionality for frisbee connections

- CHANGELOG.md
- client.go
- client_test.go
- conn.go
- conn_test.go
- options.go
- options_test.go
- server.go
- server_test.go
This adds TLS functionality to Frisbee
Completes LOOP-103
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`), 
```shell
goos: darwin
goarch: amd64
pkg: github.com/loophole-labs/frisbee
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz …
```
> Feature: LOOP-103-tls-functionality-to-frisbee

- client.go
- conn.go
- conn_test.go
- frisbee.go
- internal/protocol/protocol.go
Adds stream multiplexing into frisbee, allowing for multiple raw streams of data underlying the same frisbee connection.
Fixes LOOP-106
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`), 
New Test:
Updated Tests:
```shell
goos: darwin
goarch: …
```
> Feature: LOOP-106-Stream-Multiplexing

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other.md
- async.go
- async_test.go
- client.go
- conn.go
- frisbee.go
- options.go
- options_test.go
- sync.go
- sync_test.go
When a connection is closed properly it will send a notification before it closes, and that notification will signal to a socket being *read* that the connection is closed. 
However, to detect a connection is closed when the other side does not send a close notification, you must *write* to the socket. 
Moreover, it is possible that the socket itself is still open and can be written to, however the application on the other end is not responding in a timely manner. 
Taking into account all three scenarios, to properly handle disconnected connections we must first use a read timeout before every attempt to read an async connection. If the reading times out, we should attempt to write a `PING` message to that connection. We should then wait in a *separate* goroutine for a `PONG` message to …
> fix #44 - Handing Disconnected Connections

- .trunk/trunk.yaml
- async.go
- async_test.go
- conn.go
- server.go
- sync.go
We've added two major functions to the frisbee.Conn interface:
- `Handshake`
- `HandshakeContext`
These allow for running the TLS handshake on an underlying TLS frisbee.Conn if it's required. Also changed where the connContext function was being run to generate a connection-specific contexts - guaranteed that the TLS Handshake would be complete and at least one packet would be read before the connection context was generated. 
Fixes [#13](https://app.zenhub.com/workspaces/loophole-labs-61d69c9aa0a1140011fbdff4/issues/loopholelabs/lynk/139)
N/A
Frisbee tries to adhere to strict performance requirements, so please make sure to run `go test -bench=. ./...` and paste the results …
> (Fix) ConnContext TLS Handshake

- async.go
- async_test.go
- client.go
- client_test.go
- helpers_test.go
- pkg/packet/content.go
- pkg/packet/packet.go
- pkg/packet/packet_test.go
- pkg/packet/pool.go
- pkg/queue/queue_test.go
- server.go
- server_test.go
- sync.go
- sync_test.go
Fixes #67 
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`),
```shell
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee
BenchmarkAsyncThroughputPipe/32_Bytes-10                  127966              9602 ns/op         333.26 MB/s …
```
> (feat) Packet Content is Writable

- .trunk/trunk.yaml
- CHANGELOG.md
- async.go
- async_test.go
- client.go
- client_test.go
- go.mod
- go.sum
- internal/queue/queue.go
- server.go
- server_test.go
- A `Drain` function was added to `internal/queue` to allow the `killGoroutines` function to drain the queue once it had closed it and once it had killed all existing goroutines
- The client `heartbeat` function was modified to exit early if it detected that the underlying connection had closed
- The `Async` connection type was modified to hold `stale` data once a connection is closed. The `killGoroutines` function will drain the `incoming` queue after killing all goroutines, and store those drained packets in the `Async.stale` variable - future and existing ReadPacket calls will first check whether there is …
> Fix: #70, Reads after Connection close should only error when there is no more available data

- .github/workflows/lint.yml
- .trunk/trunk.yaml
- pkg/packet/decoder.go
- pkg/packet/decoder_test.go
- pkg/packet/packet_test.go
- protoc-gen-frisbee/templates/decode.templ
This PR changes the `pkg/packet` package and removes the decoder's dependency on the `packet.Packet` structure. Instead it's now possible to pass in a byte slice directly into the decoder. It also updates the RPC template for creating decoders for structs to use the new decoder API. 
This change also updates the trunk linter to v0.10.0-beta. 
All test cases in `decoder_test.go` have been updated
```shell
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee
BenchmarkAsyncThroughputPipe/32_Bytes-10           98272             10464 …
```
> Feat: Decoder not Dependant on packet.packet

- CHANGELOG.md
- go.mod
- protoc-gen-frisbee/pkg/generator/generator.go
- protoc-gen-frisbee/templates/templates.go
This PR changes the RPC generator to embed the template files into the protoc plugin binary and then generate templates using that embedded template filesystem instead of the OS filesystem. 
Fixes #94 
N/A
N/A
> Fix(#94) - Fixing Missing Templates 

- .github/workflows/benchmarks.yaml
- .github/workflows/tests.yml
- CHANGELOG.md
- protoc-gen-frisbee/templates/client.templ
- protoc-gen-frisbee/templates/decode.templ
- protoc-gen-frisbee/templates/server.templ
As part of Lynk we want the ability to encode and decode arbitrary structs to byte slices and vice-versa. By removing the dependency on `*packet.Packet` from all the generated decode logic, we are able to achieve this automatically using the RPC framework. 
N/A
N/A
> Feat: Generated RPC Code does not rely on *packet.Packet for decoding

- .trunk/trunk.yaml
- CHANGELOG.md
- protoc-gen-frisbee/templates/decode.templ
This PR is 2 LOC but it moves the returning of the `packet.Decoder` from inside the `decode` function (the internal decoder) to the external decode function (`Decode`). This allows us to guarantee that the decoder will not be returned to the pool until after it is finished being used. 
Fixes #102 
This bug will be addressed as part of #91 
N/A
> Fix: #102 - Fixing the packet decoder 

- CHANGELOG.md
- protoc-gen-frisbee/dockerfile
- Fixing issue where packet.Decoder would return the decoder back to the pool before decoding was complete (Issue #102)
- Updating Trunk Linter to `v0.10.1-beta`
> (Staging) Release v0.4.5

- .trunk/trunk.yaml
- CHANGELOG.md
- protoc-gen-frisbee/dockerfile
- protoc-gen-frisbee/templates/decode.templ
- Fixing issue where packet.Decoder would return the decoder back to the pool before decoding was complete (Issue #102)
- Updating Trunk Linter to `v0.10.1-beta`
> Release v0.4.5

- protoc-gen-frpc/examples/norpc/norpc.proto
- protoc-gen-frpc/examples/noservice/noservice.proto
- protoc-gen-frpc/pkg/generator/generator.go
- protoc-gen-frpc/pkg/generator/imports.go
- protoc-gen-frpc/templates/base.templ
- protoc-gen-frpc/templates/errors.templ
- protoc-gen-frpc/templates/imports.templ
- protoc-gen-frpc/templates/server.templ
FRPC crashes when the number of services in a proto3 file is 0, or when the total number of methods across all defined services is 0. 
Fixes #101 
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`),
N/A
N/A
> Fix: #101 - RPC generation when the number of services is 0

- async_test.go
- server.go
- server_test.go
This PR fixes an issue where the Frisbee server would accidentally overwrite various connections with one another because of a pointer reuse issue. 
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`),
```shell
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee
BenchmarkAsyncThroughputPipe/32_Bytes-10           98193             10480 ns/op         305.36 MB/s         458 B/op          8 allocs/op …
```
> Fix: Multiple connections

- .trunk/.gitignore
- CHANGELOG.md
- server.go
This PR gives us the ability to override the handler table before starting the server. 
N/A
> Adding SetHandlerTable function

- async.go
- async_test.go
- conn.go
- throughput_test.go
This PR increases the default deadline for Frisbee async connections and makes the default deadline editable. 
> Increasing deadline

- CHANGELOG.md
- async_test.go
- client.go
- client_test.go
- conn.go
- doc.go
- frisbee.go
- go.mod
- go.sum
- options.go
- options_test.go
- server.go
- server_test.go
- sync_test.go
- throughput_test.go
This PR allows the server to be configured to provide concurrent packet processing on a per-connection basis. 
The concurrency value of `1` specifies that a single goroutine should handle all incoming packets for a connection and process them synchronously. When the concurrency is set to `0` (the default), we're specifying that an unlimited number of goroutines can be spawned to handle incoming packets from connections, and a concurrency value of > 1 sets a limit to the number of goroutines that can be created to concurrently handle packets.
Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`),
and if required please add …
> feat: Add Concurrent Packet Handling 

- .trunk/.gitignore
- .trunk/trunk.yaml
- async.go
- async_test.go
- client.go
- conn.go
- frisbee.go
- options.go
- options_test.go
- server.go
- sync.go
Frisbee currently has a very complex timeout mechanism for heartbeats that adds a lot of complexity and processing overhead that doesn't really need to be there. 
The current logic is to wait for a connection read to timeout and then send a PING Packet and start a goroutine to watch for a PONG packet - then unblock the read goroutine and continue like normal. Then when a PONG packet is received, clear the ping timer and exit the started goroutine - otherwise if the PONG packet is not received in time, the goroutine will kill the connection. 
This is inefficient for many reasons but most importantly because the frisbee client ALSO runs a heartbeat goroutine that sends a heartbeat packet to the server periodically but only if the buffer is empty. 
This PR simplifies the whole process by a …
> Feat: Simplifying Ping/Heartbeat semantics

- CHANGELOG.md
- server.go
This PR allows users to add a custom listener to start frisbee servers.
Fixes #155 
> Feat: Adding custom listener with `StartWithListener`

- async.go
- stream.go
- stream_test.go
This PR fixes a deadlock that would occur if the connection was closed before its streams were. 
It also adds an additional test case to avoid regressions.
> Bug: Fixing Deadlock on Connection Close

- async.go
- client.go
- client_test.go
- server.go
- server_test.go
This PR creates some very breaking changes, but brings the overall implementation of the frisbee client and server inline with what one would expect, while filling some gaps in our implementation with regards to thread safety.
The firs thing this PR does is modifies stream management within the context of a server or client to properly make use of the base context for a server or client when handling new streams - this means the `SetStreamHandler` functions of both the client and the server now accept a context. This context will also now automatically be cancelled if the client or server is closed (or if the underlying client connection is ever closed). 
This PR also adds a new `StreamContext` option that allows user to override how contexts for streams get created, as well as what …
> feat: context-managed streams

- async.go
The previous implementation had a couple of issues that could cause closeWithError() to not propagate the passed error properly.
1. c.error.Store() is only called after c.close(), which could cause the channel returned by CloseChannel() to be closed before the error is set. Callers that that block on the channel may attempt to read the error before it is set.
2. If c.close() fails, closeError is returned, but not set to c.error.Store(), causing callers to miss it. Additionally, the original error is ignored and not made available to callers at all.
To fix these issues, closeWithError() is updated to set c.error before calling c.close() and all errors are returned and set to c.error by using errors.Join().
In order to support different kinds of concrete error types, the type of the error …
> async: ensure connection close error is set

- async.go
- async_test.go
- client_test.go
- conn.go
- frisbee.go
- pkg/metadata/metadata.go
- pkg/metadata/metadata_test.go
- pkg/packet/packet.go
- pkg/packet/packet_test.go
- server_test.go
- sync.go
- sync_test.go
- testutil.go
- throughput_test.go
Add magic header bytes and a maximum content length to improve how we handle unexpected packets. Connections that violate these requirements are closed immediately before their contents are processed.
> Improve handling of unexpected packets
